### PR TITLE
Create index of exercises

### PR DESCRIPTION
**Pull request by hageboeck**
Replicate the work for the `goodpractice` environment to create a list of exercises. The current list is:

image

**NB**: The "Exercise time" on the left is already fixed.

Do you know of an exercise that I might have missed?
@bernhardmgruber @sponce

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
For some reason, the templates exercise still appear as "Exercise time" in your table of exercises.

**Comment by bernhardmgruber** [comment]
Some of the exercise names start lowercase. I wonder whether we should make them uppercase. At least the ones which are not literal names of tools. So at least `Smart pointers` :)

**Comment by bernhardmgruber** [comment]
The modules exercises are missing. But because I have not added an exercise box for them :D Will fix that!

**Comment by bernhardmgruber** [comment]
Address sanitizer exercise is missing.

**Comment by bernhardmgruber** [comment]
Oh yeah, we have two outstanding exercises in #282 and #244.

**Comment by hageboeck** [comment]
> For some reason, the templates exercise still appear as "Exercise time" in your table of exercises.

Usually, you need to compile twice, because in the first pass, the index gets recreated, and typeset in the second. I have a version where it shows up correctly.

**Comment by hageboeck** [comment]
I'll merge like this to unblock other PRs. Suggestions for improving this are welcome as additional PRs!

**Pull request merged**
