### PR TITLE
WIP: create new cheatsheet for essentials course

### PR DESCRIPTION
**Pull request by roiser**
compiled a new cheatsheet for the essentials course

@bernhardmgruber the "operators" exercise does not have an explanation yet, could you please add it?

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
> @bernhardmgruber the "operators" exercise does not have an explanation yet, could you please add it?

It's in #112 since yesterday. Nobody merged it so far.

**Comment by bernhardmgruber** [comment]
Please rebase, since #112 was merged.

**Comment by hageboeck** [comment]
I was wondering if we could do with one cheat sheet for both courses?

What do you think @roiser @bernhardmgruber ?

**Comment by roiser** [comment]
i did split it into two documents for practical reasons, i.e. a mentor would need to have only this or the other one for a given course, but if we clearly make the distinction in the same doc it should also work. I leave it up to you.

**Comment by chavid** [comment]
Some progress here ? I do not fully understand what exercises are expected to be done on day 1, 2 and 3...

**Comment by roiser** [comment]
@chavid the list should be the one in the new file [ExercisesCheatSheet_TheEssentials.md](https://github.com/hsf-training/cpluspluscourse/pull/114/files#diff-30ef7d552b14010be364d875e320dc0a111f7dc38e0326d314d01723c85edb3e)

**Comment by roiser** [comment]
I had to merge in the end, but think it should be fine now.

**Pull request merged**
