### PR TITLE
Add some useful gdb commands

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Students asked me to list the more important commands to solve the debug exercise. Here is what I collected.

How should we best present these? Here in the README.md of the exercise? And what should we do about `lldb`?

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Mention this helper for migrating from gdb to lldb: https://lldb.llvm.org/use/map.html. Courtesy of @pcanal.

**Comment by hageboeck** [comment]
Very useful commands, indeed. I would add
```
info br: list active breakpoints
enable/disable/delete #: Enable/disable/delete breakpoints
```

**Comment by bernhardmgruber** [comment]
> Very useful commands, indeed. I would add

Done, thx!

**Review by hageboeck — APPROVED** [review]
Good to merge for me.

**Pull request merged**
