### PR TITLE
Port Windows guide from Google Docs

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Extended information on WSL setup.
    Added section on using lxplus via ssh.
    Added section on Visual Studio.
    Separted information on VS Code.
    Add information on using VS Code with lxplus.

Previous document: https://docs.google.com/document/d/116zgnclhQDDVW3Lb9alMbCzvsy-NpBKXhMdSO_GVJR4

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
I have to revisit the guide when I am at home on my Windows notebook, so I can verify that some things still work.

**Comment by sponce** [comment]
Is it really still draft ? Looks fine to me, providing the only error in cheks in unrelated (and now fixed anyway)

**Comment by sponce** [comment]
ok, then it's really draft. No problem

**Comment by bernhardmgruber** [comment]
I wonder whether we should even provide instructions for MinGW anymore. WSL is so much better, because it provides all the Linux tools as well. Any objections to drop MinGW?

**Comment by bernhardmgruber** [comment]
I played around with VS Code and the instructions should work. The WSL setup probably also works, but I did not test it because it would be too much work to remove my entire WSL and reinstall it. Using `ssh` directly from Windows to go to lxplus also works.

The only thing I did not test was MinGW. As I said, I would propose to remove it.

**Review by sponce — APPROVED** [review]
Looks good, but again, feel free to remove the MinGW part

**Comment by bernhardmgruber** [comment]
> Looks good, but again, feel free to remove the MinGW part

Thx, I removed the MinGW part.

**Pull request merged**
