### PR TITLE
Add credits for the coroutine graph

### PR DESCRIPTION
**Pull request by sponce**

### CODE REVIEW

**Review by bernhardmgruber — CHANGES_REQUESTED** [review]
Please fix the spelling errors reported by the pre-commit hook. You can also install it locally, so it does not let you commit without fixing the spelling errors. For this you need to install `pre-commit` and run `pre-commit install` in the repository.

**Comment by sponce** [comment]
I've now setup pre-commit properly. I thought it was already, but somehow was not. Should be fine from now

**Comment by bernhardmgruber** [comment]
I am trying to address the failing pre-commit.ci here: #260.

**Comment by sponce** [comment]
I do not get one thing : how did the codespell succeed for me locally ???

**Comment by bernhardmgruber** [comment]
I think that i may have only checked your changes and those were fine. The spell mistakes were already introduced earlier. E.g. there are spelling issues in ranges, which are outside this PR. Maybe it was also causes by the recent update of codespell/pre-commit.

**Pull request merged**
