### PR TITLE
Create a "basic" version of this course

### PR DESCRIPTION
**Pull request by sponce**
by default the full version is created, but setting boolean "onlybasics" to "true" in the main C++Course.tex file changes this.

### CODE REVIEW

**Comment by hageboeck** [comment]
I had a first look at the basic course.

This is what I noticed:
- [ ] Slide 83. Exercise regarding the compiler chain, but we are going to `code/polymorphism` to try it out. Maybe it's better to take a different example, since OO wasn't discussed yet?
- [ ] Exercise `randomise` (a.k.a. debugging) uses heap allocation of an array, but that's first (?) discussed in OO.
- [ ] 210 we're `move`ing `unique_ptr` without having explained what `move` is

**Comment by sponce** [comment]
I see that the move of chapters around is creating a couple of issues indeed. Not sure how to handle it in general. In the particular cases you raise :
  - for the compiler chain exercise, indeed, pretty much any code would do, so we could (and thus should) reuse another exercise
  - for the debug exercise, I'm not sure that missing the concept of heap is too problematic for the exercise. The essential point is to find out the bug which is somehow a syntax error, leading to a bad size
  - for the unique_ptr, it's complicated. We are presenting unique_ptr without the move semantic. There is a certain level of contradiction here, so we cannot avoid really the problem. This only points out that modern C++ without move is a no go. Not sure what to decide here.

**Comment by hageboeck** [comment]
> I see that the move of chapters around is creating a couple of issues indeed. Not sure how to handle it in general. In the particular cases you raise :
> 
> * for the compiler chain exercise, indeed, pretty much any code would do, so we could (and thus should) reuse another exercise

OK, maybe let's just go to the functions exercise, then. It's the first after `hello`, and it includes a header, which you would see when the preprocessor is done with it. I just pushed two commits that are doing just that.

> * for the debug exercise, I'm not sure that missing the concept of heap is too problematic for the exercise. The essential point is to find out the bug which is somehow a syntax error, leading to a bad size

That's probably right. We can leave it to the tutors, I guess.

> * for the unique_ptr, it's complicated. We are presenting unique_ptr without the move semantic. There is a certain level of contradiction here, so we cannot avoid really the problem. This only points out that modern C++ without move is a no go. Not sure what to decide here.

In the end, we might get away with explaining `std::move` as "I am willing to give up ownership now". Should we add a slide?

**Comment by sponce** [comment]
So we are left with the issue of `unique_ptr` being presented without move semantic. Reading back slide 210, I see that below bullet "has only move semantic", we have a subbullet "the pointer is only owned once", which basically covers more or less the basic course by stating what it means.  The example code even has a comment "transfer of ownership" on the `std::move` call. Providing we skip the quizz just after (maybe I should make it disappear in the basic course ?), I think it's kind of fine at the end.

What do you think @hageboeck ? If you're happy like this, I merge this

**Pull request merged**
